name: Deploy server
    
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: yarn
      working-directory: ./server
    - run: ./_scripts/heroku_deploy.sh server click-be
      env:
        HEROKU_API_KEY: ${{ secrets.heroku_api_key }}
