# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
    
on:
  push:
#     paths: 
#       - frontend/**
    branches: [ master ]
  pull_request:
#     paths: 
#       - frontend/**
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
      working-directory: ./frontend
    - run: yarn build-css
      working-directory: ./frontend
    - run: yarn build
      working-directory: ./frontend
    - run: yarn test --passWithNoTests
      working-directory: ./frontend
      env:
        CI: true
