name: Frontend CI
    
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
      working-directory: ./frontend
    - run: yarn build
      working-directory: ./frontend
    - run: yarn eslint
      working-directory: ./frontend
    - run: yarn test --passWithNoTests
      working-directory: ./frontend
      env:
        CI: true
